---
version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  # markdown-markdownlint: &markdown-markdownlint
  #   lint-command: 'markdownlint -s -c %USERPROFILE%\.markdownlintrc'
  #   lint-stdin: true
  #   lint-formats:
  #     - '%f:%l %m'
  #     - '%f:%l:%c %m'
  #     - '%f: %l: %m'
  checkmake-lint: &checkmake-lint
    lint-command: "checkmake"
    lint-stdin: true

  prettier-format-markdown: &prettier-format-markdown
    format-command: "prettier --parser markdown"
    format-stdin: true

  prettier-format-yaml: &prettier-format-yaml
    format-command: "prettier --parser yaml"
    format-stdin: true

  redpen-lint-core: &redpen-lint-core
    prefix: redpen
    lint-command: "redpen -l 9999 -r plain ${INPUT}"
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l: Validation%t%*[a-z][%*[a-zA-Z]], %m at line:%r"
    root-markers:
      - redpen-conf.xml
      - redpen-conf-??.xml

  redpen-text-lint: &redpen-text-lint
    <<: *redpen-lint-core
    lint-command: "redpen -l 9999 -f plain -r plain ${INPUT}"

  shellcheck-lint: &shellcheck-lint
    lint-command: "shellcheck -f gcc -x"
    lint-source: "shellcheck"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  shellcheck-lint-zsh: &shellcheck-lint-zsh
    lint-command: "shellcheck -f gcc -x --shell=bash"
    lint-source: "shellcheck"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  shfmt-format: &shfmt-format
    format-command: "shfmt -ci -s -bn"
    format-stdin: true

  vale-lint: &vale-lint
    prefix: vale
    lint-command: "vale --output=line ${INPUT}"
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c:%*[^:]:%m"

languages:
  bash:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  make:
    - <<: *checkmake-lint

  markdown:
    - <<: *prettier-format-markdown

  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  text:
    - <<: *redpen-text-lint
    - <<: *vale-lint

  yaml:
    - <<: *prettier-format-yaml

  zsh:
    - <<: *shellcheck-lint-zsh
